//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Services.Delegation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Services.Delegation.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Employees.
        /// </summary>
        public static string AssignedEmployeesTitle {
            get {
                return ResourceManager.GetString("AssignedEmployeesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        public static string AuthoritiesColumnTitle {
            get {
                return ResourceManager.GetString("AuthoritiesColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        public static string AuthoritiesTitle {
            get {
                return ResourceManager.GetString("AuthoritiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegation Comleted Successfully.
        /// </summary>
        public static string DelegationComletedSuccessfully {
            get {
                return ResourceManager.GetString("DelegationComletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegation Service.
        /// </summary>
        public static string DelegationServiceTitle {
            get {
                return ResourceManager.GetString("DelegationServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegatio No. ({0})Details.
        /// </summary>
        public static string DelegationTitleWithNO {
            get {
                return ResourceManager.GetString("DelegationTitleWithNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description Already Delegated.
        /// </summary>
        public static string JobDescriptionAlreadyDelegated {
            get {
                return ResourceManager.GetString("JobDescriptionAlreadyDelegated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authorities for selected job describtion....
        /// </summary>
        public static string NoAuthoritiesMsg {
            get {
                return ResourceManager.GetString("NoAuthoritiesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No roles for selected job describtion....
        /// </summary>
        public static string NoRolesMsg {
            get {
                return ResourceManager.GetString("NoRolesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Position...
        /// </summary>
        public static string PleaseSelectPositionMsg {
            get {
                return ResourceManager.GetString("PleaseSelectPositionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesColumnTitle {
            get {
                return ResourceManager.GetString("RolesColumnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RolesTitle {
            get {
                return ResourceManager.GetString("RolesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Authorities.
        /// </summary>
        public static string SelectAllAuthoritiesCheckBox {
            get {
                return ResourceManager.GetString("SelectAllAuthoritiesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Roles.
        /// </summary>
        public static string SelectAllRolesCheckBox {
            get {
                return ResourceManager.GetString("SelectAllRolesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Employee.
        /// </summary>
        public static string SelectEmployeeMsg {
            get {
                return ResourceManager.GetString("SelectEmployeeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select At Least one authority or one role.
        /// </summary>
        public static string SelectOneAuthorityOrRole {
            get {
                return ResourceManager.GetString("SelectOneAuthorityOrRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position.
        /// </summary>
        public static string SelectPositionMsg {
            get {
                return ResourceManager.GetString("SelectPositionMsg", resourceCulture);
            }
        }
    }
}
