//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Personnel.ValueObjects.Training {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TrainingRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrainingRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Personnel.ValueObjects.Training.TrainingRules", typeof(TrainingRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issuance date is required.
        /// </summary>
        public static string CertificateIssuanceDateReq {
            get {
                return ResourceManager.GetString("CertificateIssuanceDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to issuance date can&apos;t be greater than current date.
        /// </summary>
        public static string CertificateIssuanceDateRule1 {
            get {
                return ResourceManager.GetString("CertificateIssuanceDateRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course duration nust be greater than zero.
        /// </summary>
        public static string CourseDurationRule1 {
            get {
                return ResourceManager.GetString("CourseDurationRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course duration must be number.
        /// </summary>
        public static string CourseDurationRule2 {
            get {
                return ResourceManager.GetString("CourseDurationRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course duration can&apos;t be greater than 900.
        /// </summary>
        public static string CourseDurationRule3 {
            get {
                return ResourceManager.GetString("CourseDurationRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to course duration must be number.
        /// </summary>
        public static string CourseDurationRule4 {
            get {
                return ResourceManager.GetString("CourseDurationRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status is required.
        /// </summary>
        public static string StatusReq {
            get {
                return ResourceManager.GetString("StatusReq", resourceCulture);
            }
        }
    }
}
