//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.ProjectManagment.ValueObjects.ProjectEvaluation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProjectEvaluationModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectEvaluationModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.ProjectManagment.ValueObjects.ProjectEvaluation.ProjectEvaluation" +
                            "Model", typeof(ProjectEvaluationModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Of Completion.
        /// </summary>
        public static string CompletionPercentage {
            get {
                return ResourceManager.GetString("CompletionPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated Phases.
        /// </summary>
        public static string EvaluatedPhasePluralTitle {
            get {
                return ResourceManager.GetString("EvaluatedPhasePluralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated Phase.
        /// </summary>
        public static string EvaluatedPhaseSingleTitle {
            get {
                return ResourceManager.GetString("EvaluatedPhaseSingleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated Tasks.
        /// </summary>
        public static string EvaluatedTaskPluralTitle {
            get {
                return ResourceManager.GetString("EvaluatedTaskPluralTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluated Task.
        /// </summary>
        public static string EvaluatedTaskSingleTitle {
            get {
                return ResourceManager.GetString("EvaluatedTaskSingleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluator.
        /// </summary>
        public static string Evaluator {
            get {
                return ResourceManager.GetString("Evaluator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string EvaluatorPosition {
            get {
                return ResourceManager.GetString("EvaluatorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Role.
        /// </summary>
        public static string EvaluatorProjectRole {
            get {
                return ResourceManager.GetString("EvaluatorProjectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Evaluation Details.
        /// </summary>
        public static string ProjectEvaluationMasterGridTitle {
            get {
                return ResourceManager.GetString("ProjectEvaluationMasterGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Project Rate.
        /// </summary>
        public static string TotalProjectRate {
            get {
                return ResourceManager.GetString("TotalProjectRate", resourceCulture);
            }
        }
    }
}
