//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.OrgChart.Views.Shared.Ribbon.Functions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Functions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Functions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.OrgChart.Views.Shared.Ribbon.Functions.Functions", typeof(Functions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        public static string AssetsTitle {
            get {
                return ResourceManager.GetString("AssetsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Information.
        /// </summary>
        public static string BasicInformationTitle {
            get {
                return ResourceManager.GetString("BasicInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Benefits.
        /// </summary>
        public static string CashBenefitsTitle {
            get {
                return ResourceManager.GetString("CashBenefitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Deductions.
        /// </summary>
        public static string CashDeductionsTitle {
            get {
                return ResourceManager.GetString("CashDeductionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        public static string GradesSectionTitle {
            get {
                return ResourceManager.GetString("GradesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        public static string GradeTitle {
            get {
                return ResourceManager.GetString("GradeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurances.
        /// </summary>
        public static string InsurancesTitle {
            get {
                return ResourceManager.GetString("InsurancesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string NodeSectionTitle {
            get {
                return ResourceManager.GetString("NodeSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Services.
        /// </summary>
        public static string NodeServicesTitle {
            get {
                return ResourceManager.GetString("NodeServicesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node.
        /// </summary>
        public static string NodeTitle {
            get {
                return ResourceManager.GetString("NodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Node Type &amp; Order.
        /// </summary>
        public static string NodeTypeOrderTitle {
            get {
                return ResourceManager.GetString("NodeTypeOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NonCash Benefits.
        /// </summary>
        public static string NonCashBenefitsTitle {
            get {
                return ResourceManager.GetString("NonCashBenefitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Hierarchy.
        /// </summary>
        public static string OrganizationHierarchyTitle {
            get {
                return ResourceManager.GetString("OrganizationHierarchyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationSectionTitle {
            get {
                return ResourceManager.GetString("OrganizationSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationTitle {
            get {
                return ResourceManager.GetString("OrganizationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionSectionTitle {
            get {
                return ResourceManager.GetString("PositionSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionTitle {
            get {
                return ResourceManager.GetString("PositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign.
        /// </summary>
        public static string ReassignTitle {
            get {
                return ResourceManager.GetString("ReassignTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder.
        /// </summary>
        public static string ReorderTitle {
            get {
                return ResourceManager.GetString("ReorderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Node.
        /// </summary>
        public static string SelectNodeTitle {
            get {
                return ResourceManager.GetString("SelectNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position.
        /// </summary>
        public static string SelectPositionTitle {
            get {
                return ResourceManager.GetString("SelectPositionTitle", resourceCulture);
            }
        }
    }
}
