//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Objective.Entities.OrganizationalObjective {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OrganizationalObjectiveModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganizationalObjectiveModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Objective.Entities.OrganizationalObjective.OrganizationalObjectiv" +
                            "eModel", typeof(OrganizationalObjectiveModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Drag &amp; Drop Organizational Objective You Want To
        /// Bind With Objective.
        /// </summary>
        public static string AssignOrganizational {
            get {
                return ResourceManager.GetString("AssignOrganizational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description must be a text with a maximum length of 255 characters.
        /// </summary>
        public static string DescriptionLength {
            get {
                return ResourceManager.GetString("DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective Name.
        /// </summary>
        public static string ObjectiveName {
            get {
                return ResourceManager.GetString("ObjectiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to objective name is required.
        /// </summary>
        public static string ObjectiveNameReq {
            get {
                return ResourceManager.GetString("ObjectiveNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Objective Basic Information.
        /// </summary>
        public static string OrganizationalObjectivBasicInfo {
            get {
                return ResourceManager.GetString("OrganizationalObjectivBasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Objectives.
        /// </summary>
        public static string OrganizationalObjective {
            get {
                return ResourceManager.GetString("OrganizationalObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organizational Objective No..
        /// </summary>
        public static string OrganizationalObjectiveNo {
            get {
                return ResourceManager.GetString("OrganizationalObjectiveNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Organizational Objectives.
        /// </summary>
        public static string SelectOrganizational {
            get {
                return ResourceManager.GetString("SelectOrganizational", resourceCulture);
            }
        }
    }
}
