//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Personnel.Views.Shared.Ribbon._1stLevel {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Functions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Functions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Personnel.Views.Shared.Ribbon._1stLevel.Functions", typeof(Functions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Details.
        /// </summary>
        public static string BasicDetails {
            get {
                return ResourceManager.GetString("BasicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convictions.
        /// </summary>
        public static string Convictions {
            get {
                return ResourceManager.GetString("Convictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependents.
        /// </summary>
        public static string Dependents {
            get {
                return ResourceManager.GetString("Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving License.
        /// </summary>
        public static string DrivingLicense {
            get {
                return ResourceManager.GetString("DrivingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        public static string Experiences {
            get {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Details.
        /// </summary>
        public static string FamilyDetails {
            get {
                return ResourceManager.GetString("FamilyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifications.
        /// </summary>
        public static string Identifications {
            get {
                return ResourceManager.GetString("Identifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Service.
        /// </summary>
        public static string MilitaryService {
            get {
                return ResourceManager.GetString("MilitaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passports.
        /// </summary>
        public static string Passports {
            get {
                return ResourceManager.GetString("Passports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residencies.
        /// </summary>
        public static string Residencies {
            get {
                return ResourceManager.GetString("Residencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Skills.
        /// </summary>
        public static string TrainingSkills {
            get {
                return ResourceManager.GetString("TrainingSkills", resourceCulture);
            }
        }
    }
}
