//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Personnel.ValueObjects.Experience {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExperienceModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExperienceModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Personnel.ValueObjects.Experience.ExperienceModel", typeof(ExperienceModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Location.
        /// </summary>
        public static string CompanyLocation {
            get {
                return ResourceManager.GetString("CompanyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company location must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string CompanyLocationLength {
            get {
                return ResourceManager.GetString("CompanyLocationLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string CompanyNameLength {
            get {
                return ResourceManager.GetString("CompanyNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company name is required.
        /// </summary>
        public static string CompanyNameReq {
            get {
                return ResourceManager.GetString("CompanyNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company WebSite.
        /// </summary>
        public static string CompanyWebSite {
            get {
                return ResourceManager.GetString("CompanyWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company website must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string CompanyWebSiteLength {
            get {
                return ResourceManager.GetString("CompanyWebSiteLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end date is required.
        /// </summary>
        public static string EndDateReq {
            get {
                return ResourceManager.GetString("EndDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to industry must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string IndustryLength {
            get {
                return ResourceManager.GetString("IndustryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to industry is required.
        /// </summary>
        public static string IndustryReq {
            get {
                return ResourceManager.GetString("IndustryReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job title must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string JobTitleLength {
            get {
                return ResourceManager.GetString("JobTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to job title is required.
        /// </summary>
        public static string JobTitleReq {
            get {
                return ResourceManager.GetString("JobTitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Reason.
        /// </summary>
        public static string LeaveReason {
            get {
                return ResourceManager.GetString("LeaveReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave reason must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string LeaveReasonLength {
            get {
                return ResourceManager.GetString("LeaveReasonLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leave reason is required.
        /// </summary>
        public static string LeaveReasonReq {
            get {
                return ResourceManager.GetString("LeaveReasonReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference contact must be a text with a maximum length of 255 characters.
        /// </summary>
        public static string NotesLength {
            get {
                return ResourceManager.GetString("NotesLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Contact.
        /// </summary>
        public static string ReferenceContact {
            get {
                return ResourceManager.GetString("ReferenceContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference contact must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string ReferenceContactLength {
            get {
                return ResourceManager.GetString("ReferenceContactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference E-Mail.
        /// </summary>
        public static string ReferenceEMail {
            get {
                return ResourceManager.GetString("ReferenceEMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference e-mail must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string ReferenceEMailLength {
            get {
                return ResourceManager.GetString("ReferenceEMailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Full Name.
        /// </summary>
        public static string ReferenceFullName {
            get {
                return ResourceManager.GetString("ReferenceFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referance full name is required.
        /// </summary>
        public static string ReferenceFullNameReq {
            get {
                return ResourceManager.GetString("ReferenceFullNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Job Title.
        /// </summary>
        public static string ReferenceJobTitle {
            get {
                return ResourceManager.GetString("ReferenceJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reference job title must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string ReferenceJobTitleLength {
            get {
                return ResourceManager.GetString("ReferenceJobTitleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to referance job title is required.
        /// </summary>
        public static string ReferenceJobTitleReq {
            get {
                return ResourceManager.GetString("ReferenceJobTitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start date is required.
        /// </summary>
        public static string StartDateReq {
            get {
                return ResourceManager.GetString("StartDateReq", resourceCulture);
            }
        }
    }
}
