//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Personnel.ValueObjects.Experience {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExperienceRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExperienceRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Personnel.ValueObjects.Experience.ExperienceRules", typeof(ExperienceRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid company website.
        /// </summary>
        public static string CompanyWebSiteRule1 {
            get {
                return ResourceManager.GetString("CompanyWebSiteRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end sate is required.
        /// </summary>
        public static string EndDateReq {
            get {
                return ResourceManager.GetString("EndDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end date can not be greater than current date.
        /// </summary>
        public static string EndDateRule1 {
            get {
                return ResourceManager.GetString("EndDateRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid e-mail.
        /// </summary>
        public static string ReferenceEMailRule1 {
            get {
                return ResourceManager.GetString("ReferenceEMailRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start sate is required.
        /// </summary>
        public static string StartDateReq {
            get {
                return ResourceManager.GetString("StartDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start date must be less than end date.
        /// </summary>
        public static string StartDateRule1 {
            get {
                return ResourceManager.GetString("StartDateRule1", resourceCulture);
            }
        }
    }
}
