//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Portal.JobDescriptionSection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobDescriptionSection {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobDescriptionSection() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Portal.JobDescriptionSection.JobDescriptionSection", typeof(JobDescriptionSection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Job Description To a position.
        /// </summary>
        public static string AssignJobDescToPosition {
            get {
                return ResourceManager.GetString("AssignJobDescToPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Job Description Already Without Position !.
        /// </summary>
        public static string JobDescWithoutPositionMessage {
            get {
                return ResourceManager.GetString("JobDescWithoutPositionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Descriptions With Out Position List.
        /// </summary>
        public static string JobDescWithOutPositionTitle {
            get {
                return ResourceManager.GetString("JobDescWithOutPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Job Descriptions With Out A Position.
        /// </summary>
        public static string ListOfJobDescriptionsWithOutPositionTitle {
            get {
                return ResourceManager.GetString("ListOfJobDescriptionsWithOutPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (code:{0}).
        /// </summary>
        public static string NodeCodeValue {
            get {
                return ResourceManager.GetString("NodeCodeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Job Description Selected !.
        /// </summary>
        public static string NoJobDescriptionSelectedMessage {
            get {
                return ResourceManager.GetString("NoJobDescriptionSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Node Position(s) List.
        /// </summary>
        public static string SelectedNodePosition {
            get {
                return ResourceManager.GetString("SelectedNodePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectJobDescription ...
        /// </summary>
        public static string SelectJobDescription {
            get {
                return ResourceManager.GetString("SelectJobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select An Organization Node To Retrieve It&apos;s Position(s).
        /// </summary>
        public static string SelectOrganizationNodeTitle {
            get {
                return ResourceManager.GetString("SelectOrganizationNodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Job Descriptions Count #.
        /// </summary>
        public static string TotalJobDescriptionsCount {
            get {
                return ResourceManager.GetString("TotalJobDescriptionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Job Descriptions With Out A Position #.
        /// </summary>
        public static string TotalJobDescriptionsWithOutPosition {
            get {
                return ResourceManager.GetString("TotalJobDescriptionsWithOutPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnNamed.
        /// </summary>
        public static string UnNamedNode {
            get {
                return ResourceManager.GetString("UnNamedNode", resourceCulture);
            }
        }
    }
}
