//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.PMS.ValueObjects.TemplateCustomizedSection {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TemplateCustomizedSectionRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TemplateCustomizedSectionRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.PMS.ValueObjects.TemplateCustomizedSection.TemplateCustomizedSect" +
                            "ionRules", typeof(TemplateCustomizedSectionRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Template privent adding custom sections, Can Add Customized section not checked.
        /// </summary>
        public static string AddSectionsNotAllowed {
            get {
                return ResourceManager.GetString("AddSectionsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appraisal section evaluator field is required.
        /// </summary>
        public static string AppraisalSectionEvaluatorReq {
            get {
                return ResourceManager.GetString("AppraisalSectionEvaluatorReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to predefined section and custom sections&apos;s weight can&apos;t exceed 100..
        /// </summary>
        public static string TotalWeightRule {
            get {
                return ResourceManager.GetString("TotalWeightRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight field is required.
        /// </summary>
        public static string WeightReq {
            get {
                return ResourceManager.GetString("WeightReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight can&apos;t be negative number..
        /// </summary>
        public static string WeightRule1 {
            get {
                return ResourceManager.GetString("WeightRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight can&apos;t be greater than 100..
        /// </summary>
        public static string WeightRule2 {
            get {
                return ResourceManager.GetString("WeightRule2", resourceCulture);
            }
        }
    }
}
