//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Personnel.ValueObjects.Child {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ChildRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChildRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Personnel.ValueObjects.Child.ChildRules", typeof(ChildRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Of birth Can&apos;t Be Greater Than Current Date.
        /// </summary>
        public static string DateOfBirthRule1 {
            get {
                return ResourceManager.GetString("DateOfBirthRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport Expiry Date Can&apos;t Be Less Than Current Date.
        /// </summary>
        public static string PassportExpiryDateRule1 {
            get {
                return ResourceManager.GetString("PassportExpiryDateRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child &quot;{0}&quot; Passport Expired.
        /// </summary>
        public static string PassportExpiryDateRule2 {
            get {
                return ResourceManager.GetString("PassportExpiryDateRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passport number is required.
        /// </summary>
        public static string PassportNoRule1 {
            get {
                return ResourceManager.GetString("PassportNoRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residency Card Expiry Date Can&apos;t Be Less Than Current Date.
        /// </summary>
        public static string ResidencyExpiryDateRule1 {
            get {
                return ResourceManager.GetString("ResidencyExpiryDateRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child &quot;{0}&quot; Residence Card Expired.
        /// </summary>
        public static string ResidencyExpiryDateRule2 {
            get {
                return ResourceManager.GetString("ResidencyExpiryDateRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to residency card number is required.
        /// </summary>
        public static string ResidencyNoRule1 {
            get {
                return ResourceManager.GetString("ResidencyNoRule1", resourceCulture);
            }
        }
    }
}
