//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.JobDesc.ValueObjects.Specification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpecificationModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpecificationModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.JobDesc.ValueObjects.Specification.SpecificationModel", typeof(SpecificationModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competency.
        /// </summary>
        public static string CompetencyGridMasterTitle {
            get {
                return ResourceManager.GetString("CompetencyGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competencies.
        /// </summary>
        public static string CompetencyTitle {
            get {
                return ResourceManager.GetString("CompetencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Skill.
        /// </summary>
        public static string ComputerSkillGridMasterTitle {
            get {
                return ResourceManager.GetString("ComputerSkillGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Skills.
        /// </summary>
        public static string ComputerSkillTitle {
            get {
                return ResourceManager.GetString("ComputerSkillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string EducationGridMasterTitle {
            get {
                return ResourceManager.GetString("EducationGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educations.
        /// </summary>
        public static string EducationTitle {
            get {
                return ResourceManager.GetString("EducationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experience.
        /// </summary>
        public static string ExperienceGridMasterTitle {
            get {
                return ResourceManager.GetString("ExperienceGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        public static string ExperienceTitle {
            get {
                return ResourceManager.GetString("ExperienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge.
        /// </summary>
        public static string KnowledgeGridMasterTitle {
            get {
                return ResourceManager.GetString("KnowledgeGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge&apos;s.
        /// </summary>
        public static string KnowledgeTitle {
            get {
                return ResourceManager.GetString("KnowledgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageGridMasterTitle {
            get {
                return ResourceManager.GetString("LanguageGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skill.
        /// </summary>
        public static string SkillGridMasterTitle {
            get {
                return ResourceManager.GetString("SkillGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SkillTitle {
            get {
                return ResourceManager.GetString("SkillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string Summury {
            get {
                return ResourceManager.GetString("Summury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Condition.
        /// </summary>
        public static string WorkingConditionGridMasterTitle {
            get {
                return ResourceManager.GetString("WorkingConditionGridMasterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working Conditions.
        /// </summary>
        public static string WorkingConditionTitle {
            get {
                return ResourceManager.GetString("WorkingConditionTitle", resourceCulture);
            }
        }
    }
}
