//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.OrgChart.ValueObjects.Node {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.OrgChart.ValueObjects.Node.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Position.
        /// </summary>
        public static string AddEditPosition {
            get {
                return ResourceManager.GetString("AddEditPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add SubNode.
        /// </summary>
        public static string AddSubNode {
            get {
                return ResourceManager.GetString("AddSubNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back One Level.
        /// </summary>
        public static string BackOneLevel {
            get {
                return ResourceManager.GetString("BackOneLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Positions To Move.
        /// </summary>
        public static string ChoosePositionsToMove {
            get {
                return ResourceManager.GetString("ChoosePositionsToMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Node.
        /// </summary>
        public static string DeleteNode {
            get {
                return ResourceManager.GetString("DeleteNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Node.
        /// </summary>
        public static string EditNode {
            get {
                return ResourceManager.GetString("EditNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move All Positions.
        /// </summary>
        public static string MoveAllPositions {
            get {
                return ResourceManager.GetString("MoveAllPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodes Operations Window.
        /// </summary>
        public static string NodesOperationsWindow {
            get {
                return ResourceManager.GetString("NodesOperationsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign.
        /// </summary>
        public static string Reassign {
            get {
                return ResourceManager.GetString("Reassign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Tree.
        /// </summary>
        public static string ResetTree {
            get {
                return ResourceManager.GetString("ResetTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Order.
        /// </summary>
        public static string SetNewOrder {
            get {
                return ResourceManager.GetString("SetNewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Positions.
        /// </summary>
        public static string ShowPositions {
            get {
                return ResourceManager.GetString("ShowPositions", resourceCulture);
            }
        }
    }
}
