//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Personnel.Entities.Employee {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmployeeModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmployeeModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Personnel.Entities.Employee.EmployeeModel", typeof(EmployeeModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Group.
        /// </summary>
        public static string BloodType {
            get {
                return ResourceManager.GetString("BloodType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifications.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convictions.
        /// </summary>
        public static string Convictions {
            get {
                return ResourceManager.GetString("Convictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Of Birth.
        /// </summary>
        public static string CountryOfBirth {
            get {
                return ResourceManager.GetString("CountryOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of birth is required.
        /// </summary>
        public static string DateOfBirthReq {
            get {
                return ResourceManager.GetString("DateOfBirthReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependents.
        /// </summary>
        public static string Dependents {
            get {
                return ResourceManager.GetString("Dependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability Description.
        /// </summary>
        public static string DisabilityDescription {
            get {
                return ResourceManager.GetString("DisabilityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disability description must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string DisabilityDescriptionLength {
            get {
                return ResourceManager.GetString("DisabilityDescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability Status.
        /// </summary>
        public static string DisabilityExist {
            get {
                return ResourceManager.GetString("DisabilityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving License.
        /// </summary>
        public static string DrivingLicense {
            get {
                return ResourceManager.GetString("DrivingLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee General Info.
        /// </summary>
        public static string EmployeeGeneralInfo {
            get {
                return ResourceManager.GetString("EmployeeGeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Status.
        /// </summary>
        public static string EmployeeStatus {
            get {
                return ResourceManager.GetString("EmployeeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        public static string Experiences {
            get {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Details.
        /// </summary>
        public static string FamilyDetails {
            get {
                return ResourceManager.GetString("FamilyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name.
        /// </summary>
        public static string FatherName {
            get {
                return ResourceManager.GetString("FatherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Father Name In Arabic.
        /// </summary>
        public static string FatherNameL2 {
            get {
                return ResourceManager.GetString("FatherNameL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arabic father name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string FatherNameL2Length {
            get {
                return ResourceManager.GetString("FatherNameL2Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to father name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string FatherNameLength {
            get {
                return ResourceManager.GetString("FatherNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to father name is required.
        /// </summary>
        public static string FatherNameReq {
            get {
                return ResourceManager.GetString("FatherNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name In Arabic.
        /// </summary>
        public static string FirstNameL2 {
            get {
                return ResourceManager.GetString("FirstNameL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arabic first name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string FirstNameL2Length {
            get {
                return ResourceManager.GetString("FirstNameL2Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first name is required.
        /// </summary>
        public static string FirstNameReq {
            get {
                return ResourceManager.GetString("FirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identification Number.
        /// </summary>
        public static string IdentificationNo {
            get {
                return ResourceManager.GetString("IdentificationNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to identification number must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string IdentificationNoLength {
            get {
                return ResourceManager.GetString("IdentificationNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name In Arabic.
        /// </summary>
        public static string LastNameL2 {
            get {
                return ResourceManager.GetString("LastNameL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arabic last name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string LastNameL2Length {
            get {
                return ResourceManager.GetString("LastNameL2Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last name is required.
        /// </summary>
        public static string LastNameReq {
            get {
                return ResourceManager.GetString("LastNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string LoginNameLength {
            get {
                return ResourceManager.GetString("LoginNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login name is required.
        /// </summary>
        public static string LoginNameReq {
            get {
                return ResourceManager.GetString("LoginNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marital Status.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to marital status is required.
        /// </summary>
        public static string MaritalStatusReq {
            get {
                return ResourceManager.GetString("MaritalStatusReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name In Arabic.
        /// </summary>
        public static string MiddleNameL2 {
            get {
                return ResourceManager.GetString("MiddleNameL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arabic middle name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string MiddleNameL2Length {
            get {
                return ResourceManager.GetString("MiddleNameL2Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middle name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string MiddleNameLength {
            get {
                return ResourceManager.GetString("MiddleNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Service.
        /// </summary>
        public static string MilitaryService {
            get {
                return ResourceManager.GetString("MilitaryService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Military Service Status.
        /// </summary>
        public static string MilitaryStatus {
            get {
                return ResourceManager.GetString("MilitaryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string Miscellaneous {
            get {
                return ResourceManager.GetString("Miscellaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name.
        /// </summary>
        public static string MotherName {
            get {
                return ResourceManager.GetString("MotherName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mother Name In Arabic.
        /// </summary>
        public static string MotherNameL2 {
            get {
                return ResourceManager.GetString("MotherNameL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arabic mother name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string MotherNameL2Length {
            get {
                return ResourceManager.GetString("MotherNameL2Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mother name must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string MotherNameLength {
            get {
                return ResourceManager.GetString("MotherNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mother name is required.
        /// </summary>
        public static string MotherNameReq {
            get {
                return ResourceManager.GetString("MotherNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name In First Language.
        /// </summary>
        public static string NameInFirstLanguage {
            get {
                return ResourceManager.GetString("NameInFirstLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name In Second Language.
        /// </summary>
        public static string NameInSecondLanguage {
            get {
                return ResourceManager.GetString("NameInSecondLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationalities And Birth Information.
        /// </summary>
        public static string NationalitiesAndBirthInformation {
            get {
                return ResourceManager.GetString("NationalitiesAndBirthInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nationality is required.
        /// </summary>
        public static string NationalityReq {
            get {
                return ResourceManager.GetString("NationalityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Employee Record Selected, Select/Add One To Proceed.
        /// </summary>
        public static string NoEmployeeSelectedMessage {
            get {
                return ResourceManager.GetString("NoEmployeeSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Children.
        /// </summary>
        public static string NoOfChildren {
            get {
                return ResourceManager.GetString("NoOfChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of children is required.
        /// </summary>
        public static string NoOfChildrenReq {
            get {
                return ResourceManager.GetString("NoOfChildrenReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Dependents.
        /// </summary>
        public static string NoOfDependents {
            get {
                return ResourceManager.GetString("NoOfDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number of dependents is required.
        /// </summary>
        public static string NoOfDependentsReq {
            get {
                return ResourceManager.GetString("NoOfDependentsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Nationality.
        /// </summary>
        public static string OtherNationality {
            get {
                return ResourceManager.GetString("OtherNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passports.
        /// </summary>
        public static string Passports {
            get {
                return ResourceManager.GetString("Passports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Photo.
        /// </summary>
        public static string PersonalPhoto {
            get {
                return ResourceManager.GetString("PersonalPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Birth.
        /// </summary>
        public static string PlaceOfBirth {
            get {
                return ResourceManager.GetString("PlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place of birth is required.
        /// </summary>
        public static string PlaceOfBirthReq {
            get {
                return ResourceManager.GetString("PlaceOfBirthReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Race.
        /// </summary>
        public static string Race {
            get {
                return ResourceManager.GetString("Race", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Religion.
        /// </summary>
        public static string Religion {
            get {
                return ResourceManager.GetString("Religion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residencies.
        /// </summary>
        public static string Residencies {
            get {
                return ResourceManager.GetString("Residencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees List - Select Row For Details.
        /// </summary>
        public static string SelectEmployeeMessage {
            get {
                return ResourceManager.GetString("SelectEmployeeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Insurance Number.
        /// </summary>
        public static string SocialInsuranceNo {
            get {
                return ResourceManager.GetString("SocialInsuranceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to social insurance number must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string SocialInsuranceNoLength {
            get {
                return ResourceManager.GetString("SocialInsuranceNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Insurance Status.
        /// </summary>
        public static string SocialInsuranceNoStatus {
            get {
                return ResourceManager.GetString("SocialInsuranceNoStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number.
        /// </summary>
        public static string SocialSecurityNo {
            get {
                return ResourceManager.GetString("SocialSecurityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to social security number must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string SocialSecurityNoLength {
            get {
                return ResourceManager.GetString("SocialSecurityNoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spouse.
        /// </summary>
        public static string Spouse {
            get {
                return ResourceManager.GetString("Spouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Skills.
        /// </summary>
        public static string TrainingSkills {
            get {
                return ResourceManager.GetString("TrainingSkills", resourceCulture);
            }
        }
    }
}
