//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.Personnel.ValueObjects.Spouse {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SpouseRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SpouseRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.Personnel.ValueObjects.Spouse.SpouseRules", typeof(SpouseRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of birth is required.
        /// </summary>
        public static string DateOfBirthReq {
            get {
                return ResourceManager.GetString("DateOfBirthReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to date of birth can&apos;t be greater than current date.
        /// </summary>
        public static string DateOfBirthRule1 {
            get {
                return ResourceManager.GetString("DateOfBirthRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid e-mail.
        /// </summary>
        public static string EMailRule1 {
            get {
                return ResourceManager.GetString("EMailRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not allowed to add.. change your marital status.
        /// </summary>
        public static string IdRule1 {
            get {
                return ResourceManager.GetString("IdRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nationality is required.
        /// </summary>
        public static string NationalityReq {
            get {
                return ResourceManager.GetString("NationalityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passport has expired.
        /// </summary>
        public static string PassportExpiryDateRule1 {
            get {
                return ResourceManager.GetString("PassportExpiryDateRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passport number is required.
        /// </summary>
        public static string PassportNoRule1 {
            get {
                return ResourceManager.GetString("PassportNoRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to place of birth is required.
        /// </summary>
        public static string PlaceOfBirthReq {
            get {
                return ResourceManager.GetString("PlaceOfBirthReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to residency has expired.
        /// </summary>
        public static string ResidencyExpiryDate {
            get {
                return ResourceManager.GetString("ResidencyExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to residency card number is required.
        /// </summary>
        public static string ResidencyNoRule1 {
            get {
                return ResourceManager.GetString("ResidencyNoRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid work e-mail.
        /// </summary>
        public static string WorkEMailRule1 {
            get {
                return ResourceManager.GetString("WorkEMailRule1", resourceCulture);
            }
        }
    }
}
