//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRIS.Validation.MessageStore {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalMessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalMessagesResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HRIS.Validation.MessageStore.GlobalMessagesResource", typeof(GlobalMessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Add !!.
        /// </summary>
        internal static string CanNotAdd {
            get {
                return ResourceManager.GetString("CanNotAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Delete !!.
        /// </summary>
        internal static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Browse This Module !!.
        /// </summary>
        internal static string CanNotRead {
            get {
                return ResourceManager.GetString("CanNotRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Are Not Allowed To Update !!.
        /// </summary>
        internal static string CanNotUpdate {
            get {
                return ResourceManager.GetString("CanNotUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Delete? This action cannot be undone..
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done !.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists. Please enter a different value..
        /// </summary>
        internal static string Duplication {
            get {
                return ResourceManager.GetString("Duplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t Delete Selected Entity Since It&apos;s Currently In Use.
        /// </summary>
        internal static string EntityInUse {
            get {
                return ResourceManager.GetString("EntityInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Insert, Please Try Again Later !!.
        /// </summary>
        internal static string ErrorWhileAdd {
            get {
                return ResourceManager.GetString("ErrorWhileAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Delete ! Please try Again.
        /// </summary>
        internal static string ErrorWhileDelete {
            get {
                return ResourceManager.GetString("ErrorWhileDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error While Update, Please Try Again Later !!.
        /// </summary>
        internal static string ErrorWhileUpdate {
            get {
                return ResourceManager.GetString("ErrorWhileUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index Already In Use.
        /// </summary>
        internal static string IndexInUse {
            get {
                return ResourceManager.GetString("IndexInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Indexes.
        /// </summary>
        internal static string NoIdexes {
            get {
                return ResourceManager.GetString("NoIdexes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this operation..
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure You Want To Proceed With This Operation?.
        /// </summary>
        internal static string OperationConfirm {
            get {
                return ResourceManager.GetString("OperationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t do this because child data exits..
        /// </summary>
        internal static string ReferncesValue {
            get {
                return ResourceManager.GetString("ReferncesValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
