//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.JobDesc.Entities.JobDescription {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JobDescriptionModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JobDescriptionModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.JobDesc.Entities.JobDescription.JobDescriptionModel", typeof(JobDescriptionModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorities.
        /// </summary>
        public static string AuthorityTitle {
            get {
                return ResourceManager.GetString("AuthorityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description No. ({0}) Details.
        /// </summary>
        public static string BasicInfoTitle {
            get {
                return ResourceManager.GetString("BasicInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competencies.
        /// </summary>
        public static string CompetencyTitle {
            get {
                return ResourceManager.GetString("CompetencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description Basic Information.
        /// </summary>
        public static string CreatePageTitle {
            get {
                return ResourceManager.GetString("CreatePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educations.
        /// </summary>
        public static string EducationTitle {
            get {
                return ResourceManager.GetString("EducationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiences.
        /// </summary>
        public static string ExperienceTitle {
            get {
                return ResourceManager.GetString("ExperienceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description List - Select Row For Details.
        /// </summary>
        public static string JobDescMasterGridTitle {
            get {
                return ResourceManager.GetString("JobDescMasterGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Role.
        /// </summary>
        public static string JobRole {
            get {
                return ResourceManager.GetString("JobRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledges.
        /// </summary>
        public static string KnowledgeTitle {
            get {
                return ResourceManager.GetString("KnowledgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Languages.
        /// </summary>
        public static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | assigned to position : ({0}) :.
        /// </summary>
        public static string MessageOfJobDescriptionAssigned {
            get {
                return ResourceManager.GetString("MessageOfJobDescriptionAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | not assigned yet !.
        /// </summary>
        public static string MessageOfJobDescriptionNotAssigned {
            get {
                return ResourceManager.GetString("MessageOfJobDescriptionNotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Job Description Record Selected, Select/Add One To Proceed..
        /// </summary>
        public static string NoJobDescSelectedMessage {
            get {
                return ResourceManager.GetString("NoJobDescSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string RoleTitle {
            get {
                return ResourceManager.GetString("RoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skills.
        /// </summary>
        public static string SkillTitle {
            get {
                return ResourceManager.GetString("SkillTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        public static string SpecificationTitle {
            get {
                return ResourceManager.GetString("SpecificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to summary field must be a text with a maximum length of 510 characters.
        /// </summary>
        public static string SummaryLength {
            get {
                return ResourceManager.GetString("SummaryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Field Is Required.
        /// </summary>
        public static string SummaryReq {
            get {
                return ResourceManager.GetString("SummaryReq", resourceCulture);
            }
        }
    }
}
