//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Views.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Buttons {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Buttons() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Views.Shared.Buttons", typeof(Buttons).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Phase.
        /// </summary>
        public static string AppraisalPhase {
            get {
                return ResourceManager.GetString("AppraisalPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Section.
        /// </summary>
        public static string AppraisalSection {
            get {
                return ResourceManager.GetString("AppraisalSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal Template.
        /// </summary>
        public static string AppraisalTemplate {
            get {
                return ResourceManager.GetString("AppraisalTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Card.
        /// </summary>
        public static string EmployeeCard {
            get {
                return ResourceManager.GetString("EmployeeCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Apprisal.
        /// </summary>
        public static string LiveApprisal {
            get {
                return ResourceManager.GetString("LiveApprisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Chart.
        /// </summary>
        public static string OrganizationChart {
            get {
                return ResourceManager.GetString("OrganizationChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PMS Comprehensive.
        /// </summary>
        public static string PMSComprehensive {
            get {
                return ResourceManager.GetString("PMSComprehensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        public static string ProjectManagement {
            get {
                return ResourceManager.GetString("ProjectManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souccar HR Home.
        /// </summary>
        public static string SouccarHRHome {
            get {
                return ResourceManager.GetString("SouccarHRHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Souccar HR Portal.
        /// </summary>
        public static string SouccarHRPortal {
            get {
                return ResourceManager.GetString("SouccarHRPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Here.
        /// </summary>
        public static string StartHere {
            get {
                return ResourceManager.GetString("StartHere", resourceCulture);
            }
        }
    }
}
