//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.JobDesc.ValueObjects.Responsibility {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponsibilityRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResponsibilityRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.JobDesc.ValueObjects.Responsibility.ResponsibilityRules", typeof(ResponsibilityRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Specialization Field Is Required.
        /// </summary>
        public static string JobRoleReq {
            get {
                return ResourceManager.GetString("JobRoleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title Field Is Required.
        /// </summary>
        public static string JobTitleReq {
            get {
                return ResourceManager.GetString("JobTitleReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Field Is Required.
        /// </summary>
        public static string PriorityReq {
            get {
                return ResourceManager.GetString("PriorityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight can&apos;t be equal to zero..
        /// </summary>
        public static string WeightRule1 {
            get {
                return ResourceManager.GetString("WeightRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weight can not be greater than 100..
        /// </summary>
        public static string WeightRule2 {
            get {
                return ResourceManager.GetString("WeightRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total weight is exceeding 100...Please updat the weight in other role responsibilities and try again..
        /// </summary>
        public static string WeightRule3 {
            get {
                return ResourceManager.GetString("WeightRule3", resourceCulture);
            }
        }
    }
}
