//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.OrgChart.ValueObjects.Insurance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InsuranceModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InsuranceModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.OrgChart.ValueObjects.Insurance.InsuranceModel", typeof(InsuranceModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string CompanyAddress {
            get {
                return ResourceManager.GetString("CompanyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company address field must be a text with a maximum length of 255 characters.
        /// </summary>
        public static string CompanyAddressLength {
            get {
                return ResourceManager.GetString("CompanyAddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company address field is required.
        /// </summary>
        public static string CompanyAddressReq {
            get {
                return ResourceManager.GetString("CompanyAddressReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Company.
        /// </summary>
        public static string InsuranceCompany {
            get {
                return ResourceManager.GetString("InsuranceCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance Coverage Ratio.
        /// </summary>
        public static string InsuranceCoverageRatio {
            get {
                return ResourceManager.GetString("InsuranceCoverageRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Contact.
        /// </summary>
        public static string RepresentativeContact {
            get {
                return ResourceManager.GetString("RepresentativeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to representative contact field must be a text with a maximum length of 50 characters.
        /// </summary>
        public static string RepresentativeContactLength {
            get {
                return ResourceManager.GetString("RepresentativeContactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to representative contact field is required.
        /// </summary>
        public static string RepresentativeContactReq {
            get {
                return ResourceManager.GetString("RepresentativeContactReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
    }
}
