namespace UI.Areas.Personnel.Helpers
{
    public enum PersonnelCacheKeys
    {
        BloodType,
        Religion,
        MajorType,
        Country,
        CertificationType,
        Gender,
        MilitaryStatus,
        MaritalStatus,
        Status,
        Race,
        Nationality,
        ResidencyType,
        Bank,
        ConvictionRule,
        DriveingLicenseType,
        Level,
        Major,
        SkillType,
        MarkScale,
        BoolCondition,
        ScoreType,
        Employee,
        EmployeeWithOutPosition,
        Contact
    }
}