//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.JobDesc.ValueObjects.JEducation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JEducationRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JEducationRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.JobDesc.ValueObjects.JEducation.JEducationRules", typeof(JEducationRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major Field Is Required.
        /// </summary>
        public static string MajorReq {
            get {
                return ResourceManager.GetString("MajorReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank Field Is Required.
        /// </summary>
        public static string RankReq {
            get {
                return ResourceManager.GetString("RankReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Field Can&apos;t Equal Zero.
        /// </summary>
        public static string ScoreRule1 {
            get {
                return ResourceManager.GetString("ScoreRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Can Not Be Greater Than 100.
        /// </summary>
        public static string ScoreRule2 {
            get {
                return ResourceManager.GetString("ScoreRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score Type Field Is Required.
        /// </summary>
        public static string ScoreTypeReq {
            get {
                return ResourceManager.GetString("ScoreTypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Degree Field Is Required.
        /// </summary>
        public static string TypeReq {
            get {
                return ResourceManager.GetString("TypeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Field Can&apos;t Equal Zero.
        /// </summary>
        public static string WeightRule1 {
            get {
                return ResourceManager.GetString("WeightRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Can Not Be Greater Than 100.
        /// </summary>
        public static string WeightRule2 {
            get {
                return ResourceManager.GetString("WeightRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total weight is exceeding 100...Please updat the weight in other job description educations and try again..
        /// </summary>
        public static string WeightRule3 {
            get {
                return ResourceManager.GetString("WeightRule3", resourceCulture);
            }
        }
    }
}
