//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Areas.PMS.Entities.AppraisalPhase {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppraisalPhaseRules {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppraisalPhaseRules() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Areas.PMS.Entities.AppraisalPhase.AppraisalPhaseRules", typeof(AppraisalPhaseRules).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direct manager weight field is required.
        /// </summary>
        public static string DirectManagerWeightRule {
            get {
                return ResourceManager.GetString("DirectManagerWeightRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direct manager weight can&apos;t be smaller than 0..
        /// </summary>
        public static string DirectManagerWeightRule1 {
            get {
                return ResourceManager.GetString("DirectManagerWeightRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direct manager weight can not be greater than 100..
        /// </summary>
        public static string DirectManagerWeightRule2 {
            get {
                return ResourceManager.GetString("DirectManagerWeightRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from date can&apos;t be greater than current date.
        /// </summary>
        public static string FromDateRule {
            get {
                return ResourceManager.GetString("FromDateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full mark threshold must be less than the skill threshold.
        /// </summary>
        public static string FullMarkMustLessThanSkillThresholdRule {
            get {
                return ResourceManager.GetString("FullMarkMustLessThanSkillThresholdRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full mark threshold field is required.
        /// </summary>
        public static string FullMarkThresholdRule {
            get {
                return ResourceManager.GetString("FullMarkThresholdRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full mark threshold can&apos;t be smaller than 1..
        /// </summary>
        public static string FullMarkThresholdRule1 {
            get {
                return ResourceManager.GetString("FullMarkThresholdRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full mark threshold can not be greater than 5..
        /// </summary>
        public static string FullMarkThresholdRule2 {
            get {
                return ResourceManager.GetString("FullMarkThresholdRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gap threshold must be less than the full mark threshold.
        /// </summary>
        public static string GapMustLessThanTheFullMarkRule {
            get {
                return ResourceManager.GetString("GapMustLessThanTheFullMarkRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gap threshold field is required.
        /// </summary>
        public static string GapThresholdRule {
            get {
                return ResourceManager.GetString("GapThresholdRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gap threshold can&apos;t be smaller than 1..
        /// </summary>
        public static string GapThresholdRule1 {
            get {
                return ResourceManager.GetString("GapThresholdRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gap threshold can not be greater than 5..
        /// </summary>
        public static string GapThresholdRule2 {
            get {
                return ResourceManager.GetString("GapThresholdRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indirect manager weight field is required.
        /// </summary>
        public static string IndirectManagerWeightRule {
            get {
                return ResourceManager.GetString("IndirectManagerWeightRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indirect manager weight can&apos;t be smaller than 0..
        /// </summary>
        public static string IndirectManagerWeightRule1 {
            get {
                return ResourceManager.GetString("IndirectManagerWeightRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to indirect manager weight can not be greater than 100..
        /// </summary>
        public static string IndirectManagerWeightRule2 {
            get {
                return ResourceManager.GetString("IndirectManagerWeightRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period field is required.
        /// </summary>
        public static string PeriodReq {
            get {
                return ResourceManager.GetString("PeriodReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self assessment weight shoud be &gt; 0 when Self assessment is checked.
        /// </summary>
        public static string SelfAssessmentIsCheckedRule {
            get {
                return ResourceManager.GetString("SelfAssessmentIsCheckedRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self assessment weight field is required.
        /// </summary>
        public static string SelfAssessmentWeightRule {
            get {
                return ResourceManager.GetString("SelfAssessmentWeightRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self assessment weight can&apos;t be smaller than 0..
        /// </summary>
        public static string SelfAssessmentWeightRule1 {
            get {
                return ResourceManager.GetString("SelfAssessmentWeightRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to self assessment weight can not be greater than 100..
        /// </summary>
        public static string SelfAssessmentWeightRule2 {
            get {
                return ResourceManager.GetString("SelfAssessmentWeightRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skill threshold weight field is required.
        /// </summary>
        public static string SkillThresholdRule {
            get {
                return ResourceManager.GetString("SkillThresholdRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skill threshold can&apos;t be smaller than 1..
        /// </summary>
        public static string SkillThresholdRule1 {
            get {
                return ResourceManager.GetString("SkillThresholdRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to skill threshold can not be greater than 5..
        /// </summary>
        public static string SkillThresholdRule2 {
            get {
                return ResourceManager.GetString("SkillThresholdRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start date must be graeter than or equal to date.
        /// </summary>
        public static string StartDateRule {
            get {
                return ResourceManager.GetString("StartDateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to date can&apos;t be greater than current date.
        /// </summary>
        public static string ToDateRule {
            get {
                return ResourceManager.GetString("ToDateRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to date must be greater than from date.
        /// </summary>
        public static string ToDateRule1 {
            get {
                return ResourceManager.GetString("ToDateRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Level Grade field is required.
        /// </summary>
        public static string TopLevelGradeReq {
            get {
                return ResourceManager.GetString("TopLevelGradeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total weights of Self Assessment, Direct Manager and Indirect Manager fields must equal to 100..
        /// </summary>
        public static string TotalWeightsRule {
            get {
                return ResourceManager.GetString("TotalWeightsRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year must be less than or equal to current year.
        /// </summary>
        public static string YearRule1 {
            get {
                return ResourceManager.GetString("YearRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year must be greater than zero.
        /// </summary>
        public static string YearRule2 {
            get {
                return ResourceManager.GetString("YearRule2", resourceCulture);
            }
        }
    }
}
